export const TERMS_CONTENT = `
## 1. Acceptance of Terms

By accessing or using Strive, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform.

## 2. Description of Service

Strive is an AI-powered learning platform that generates personalized courses based on your learning goals. Content is generated by artificial intelligence and may not always be accurate or complete.

## 3. User Accounts

- You must provide accurate information when creating an account.
- You are responsible for maintaining the security of your account credentials.
- You must be at least 13 years of age to use this service.

## 4. Acceptable Use

You agree not to:

- Use the platform for any unlawful purpose.
- Attempt to interfere with or disrupt the service.
- Reverse-engineer or attempt to extract the source code of the platform.
- Share your account credentials with others.

## 5. Intellectual Property

- Course content generated by AI is provided for your personal educational use.
- The Strive platform, including its design, code, and branding, remains the property of Strive.

## 6. Limitation of Liability

Strive is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the platform, including but not limited to inaccuracies in AI-generated content.

## 7. Changes to Terms

We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the updated terms.

## 8. Contact

If you have questions about these terms, please contact us at **support@strive.com**.
`;
