export enum QKeys {
  AUTH_USER = 'authUser',
  COURSES = 'courses',
  COURSE = 'course',
  JOB = 'job',
  LESSON_CONTENT = 'lessonContent',
  COURSE_PROGRESS = 'courseProgress',
  CONTINUE_LEARNING = 'continueLearning',
  GENERATED_LESSONS = 'generatedLessons',
  PROGRESS_SUMMARY = 'progressSummary',
  MODULE_QUIZ_CONTENT = 'moduleQuizContent',
  MODULE_QUIZ_PROGRESS = 'moduleQuizProgress',
  REVIEWS_DUE = 'reviewsDue',
  UNATTEMPTED_QUIZ_COUNT = 'unattemptedQuizCount',
  FAVORITE_COURSES = 'favoriteCourses',
  BOOKMARKED_LESSONS = 'bookmarkedLessons',
  RECENT_ACTIVITY = 'recentActivity',
  GAMIFICATION_PROFILE = 'gamificationProfile',
  GAMIFICATION_STATS = 'gamificationStats',
  GAMIFICATION_QUIZ_TRENDS = 'gamificationQuizTrends',
}
