/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password for the authenticated user
         * @description Requires an existing password (CREDENTIALS provider). Bumps tokenVersion to invalidate other sessions; the caller must re-authenticate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        newPassword: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/delete-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the authenticated user's account and all associated data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                deleted: boolean;
                            };
                        };
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset link
         * @description Always responds 200 with a generic message regardless of whether the email exists, to prevent account enumeration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthorisedUser"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate or register via Google */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        idToken: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the caller's bearer token by rotating tokenVersion
         * @description Increments the user's `tokenVersion` on the server, which causes the `protect` middleware to reject any JWT minted under the previous version. The client should clear its session cookie alongside calling this endpoint. Idempotent in effect (further calls will 401 because the bearer is no longer valid).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the email verification link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                /** @description Invalid email or password. Returned identically whether the email is unknown or the password is wrong — the endpoint intentionally does not disclose which. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification-authenticated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend verification email for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password using a token from the reset email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        token: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a password on a Google-only account
         * @description Adds a password (and the CREDENTIALS provider) to an authenticated user that does not yet have one. Bumps tokenVersion, so the caller must re-authenticate after success.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        newPassword: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a user's email address */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a chat message for course structure refinement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        messages: {
                            /** @enum {string} */
                            role?: "user" | "assistant";
                            content?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description SSE stream of chat response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate clarifying questions for a course */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all courses for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new course */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        goal: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single course by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a course and its associated jobs */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                deleted: boolean;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a course by ID */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        goal?: string;
                        answers?: Record<string, never>;
                        depth?: components["schemas"]["CourseDepth"];
                        status?: components["schemas"]["CourseStatus"];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"];
                        };
                    };
                };
                /** @description Cannot transition accepted course back to creating */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/course/execute-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute code via Judge0 sandbox */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        language: string;
                        stdin?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                stdout: string | null;
                                stderr: string | null;
                                compile_output: string | null;
                                status: string;
                                time: string | null;
                                memory: number | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/depth-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate personalized depth level previews */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generate-lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate content for a specific lesson */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        moduleIndex: number;
                        lessonIndex: number;
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a module quiz (or regenerate for retakes) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generate-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate course structure with modules and lessons */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/bookmarked-lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all bookmarked lessons across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                courseName: string;
                                courseSlug: string | null;
                                moduleIndex: number;
                                lessonIndex: number;
                                moduleName: string;
                                lessonName: string;
                                /** Format: date-time */
                                bookmarkedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chat history for course structure refinement */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                messages: {
                                    /** @enum {string} */
                                    role?: "user" | "assistant";
                                    content?: string;
                                    /** Format: date-time */
                                    createdAt?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recently accessed lesson across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                courseSlug: string | null;
                                courseName: string;
                                courseGoal: string;
                                moduleName: string;
                                lessonName: string;
                                moduleIndex: number;
                                lessonIndex: number;
                                courseProgress: components["schemas"]["CourseProgressStats"];
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lesson progress for a course with aggregate stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                lessons: components["schemas"]["UserLessonProgress"][];
                                quizzes: components["schemas"]["CourseQuizProgressItem"][];
                                stats: components["schemas"]["CourseProgressStats"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/edit-impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assess the impact of editing a course (content and progress that would be lost) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                hasContent?: boolean;
                                hasProgress?: boolean;
                                completedLessons?: number;
                                inProgressLessons?: number;
                                totalNotes?: number;
                                totalBookmarks?: number;
                                quizAttempts?: number;
                                modulesWithMastery?: number;
                                scheduledReviews?: number;
                                totalTimeSpentMinutes?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of favorited course IDs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generated-lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of lessons that have generated content */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                moduleIndex: number;
                                lessonIndex: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/job/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status for polling */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["JobStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/lesson-content/{moduleIndex}/{lessonIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generated content for a specific lesson */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                    lessonIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["LessonContent"];
                        };
                    };
                };
                /** @description Lesson content not yet generated */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get module quiz content (correctIndex and explanation stripped for anti-cheat) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ModuleQuizContent"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get quiz progress (attempts, best score, mastery tier) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserModuleQuizProgress"] | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/progress-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get progress percentage for all user courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                total: number;
                                completed: number;
                                percentage: number;
                                lastModuleIndex: number | null;
                                lastLessonIndex: number | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/recent-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recently accessed lessons across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                courseSlug: string | null;
                                courseName: string;
                                moduleIndex: number;
                                lessonIndex: number;
                                moduleName: string;
                                lessonName: string;
                                /** Format: date-time */
                                lastAccessedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/reviews-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all module quizzes due for review across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ReviewDueItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/unattempted-quiz-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get module quizzes never attempted across all courses (where module lessons are complete) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                courseSlug?: string | null;
                                courseName: string;
                                moduleIndex: number;
                                moduleName: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/refine-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refine course structure based on learner feedback */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        feedback: string;
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/stream-lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate and stream lesson content via SSE (block-by-block) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        moduleIndex: number;
                        lessonIndex: number;
                    };
                };
            };
            responses: {
                /** @description SSE stream of lesson generation events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit quiz attempt — grades answers and returns results with explanations */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        responses: {
                            questionId: string;
                            selectedOption: number;
                        }[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["QuizAttemptResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/favorite/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle a course as favorite/unfavorite */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                favorited: boolean;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/progress/{moduleIndex}/{lessonIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert lesson progress (mark complete, update notes, track time, etc.) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                    lessonIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        status?: components["schemas"]["LessonProgressStatus"];
                        notes?: string | null;
                        bookmarked?: boolean;
                        /** @description Seconds to add to cumulative time */
                        timeSpentDelta?: number;
                        quizResponse?: components["schemas"]["QuizResponse"];
                        exerciseAttempt?: components["schemas"]["ExerciseAttempt"];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserLessonProgress"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gamification/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the user's gamification profile (XP, level, streak, achievements, settings) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["GamificationProfile"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gamification/quiz-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all quiz attempt scores over time for trend visualization */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gamification/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get gamification stats (XP history, time learned, weekly lessons) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["GamificationStats"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the user's daily insight queue (due items + fresh items, interleaved across courses)
         * @description When `currentCourseId` is supplied (e.g. the learner is reviewing from
         *     inside a specific lesson) the active course's items are placed first
         *     in both the due and fresh slices; cross-course items still follow.
         *     Without the param the queue is a cross-course interleave as before.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Mongo ObjectId of the course the learner is currently studying. Items from this course are surfaced first. */
                    currentCourseId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["InsightQueue"];
                        };
                    };
                };
                /** @description Invalid currentCourseId (not an ObjectId). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get per-user insight review stats (mastery dashboard) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["InsightStats"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/due-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cheap count of due insights for dashboard widgets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                count: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/{insightId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a learner's typed-recall answer against the canonical (Haiku + Levenshtein short-circuit) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    insightId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userAnswer: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["GradeResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/{insightId}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a rating for an insight and advance its scheduler state */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    insightId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 1=Again, 2=Hard, 3=Good, 4=Easy
                         * @enum {integer}
                         */
                        rating: 1 | 2 | 3 | 4;
                        /** @description Similarity score if answered via typed-recall mode */
                        typedMatch?: number | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["RateInsightResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/{insightId}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch an insight between tap-reveal and typed-recall modes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    insightId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mode: "tap-reveal" | "typed-recall";
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @enum {string} */
                                mode: "tap-reveal" | "typed-recall";
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight/{insightId}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Defer an insight by 1 day without treating it as a failed review */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    insightId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: date-time */
                                nextDue: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "CUSTOM_ERROR" | "EMAIL_NOT_VERIFIED" | "EMAIL_ALREADY_VERIFIED" | "EMAIL_VERIFICATION_EXPIRED" | "EMAIL_VERIFICATION_INVALID" | "PASSWORD_RESET_INVALID" | "PASSWORD_RESET_EXPIRED" | "PASSWORD_ALREADY_SET" | "PASSWORD_NOT_SET";
        /** @enum {string} */
        AuthProviderType: "GOOGLE" | "CREDENTIALS";
        /** @enum {string} */
        QuestionType: "multiple_choice" | "multiple_select" | "text";
        /** @enum {string} */
        CourseDepth: "overview" | "comprehensive" | "deep_dive";
        /** @enum {string} */
        CourseStatus: "creating" | "ready" | "archived";
        /** @enum {string} */
        CourseDomain: "programming" | "stem" | "humanities" | "language" | "creative" | "business" | "practical" | "life-skills" | "other";
        /** @enum {string} */
        JobStatusEnum: "pending" | "processing" | "completed" | "failed";
        /** @enum {string} */
        JobType: "clarify" | "generate_structure" | "refine_structure" | "generate_lesson" | "generate_depth_previews" | "generate_module_quiz";
        /** @enum {string} */
        LessonProgressStatus: "not_started" | "in_progress" | "completed";
        /** @enum {string} */
        QuizMasteryTier: "needs_review" | "passed" | "mastered";
        /** @enum {string} */
        BlockType: "intro" | "section" | "code" | "mermaid" | "callout" | "quiz" | "exercise" | "summary" | "links" | "image";
        /** @enum {string} */
        ReviewReason: "time" | "progression";
        ApiError: {
            message: string;
            errorCode?: components["schemas"]["ErrorCode"];
        };
        AuthProvider: {
            provider: components["schemas"]["AuthProviderType"];
            providerId?: string;
        };
        AuthorisedUser: {
            _id: string;
            email: string;
            name?: string;
            image?: string;
            emailVerified: boolean;
            authProviders: components["schemas"]["AuthProvider"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClarifyQuestion: {
            id: string;
            question: string;
            type: components["schemas"]["QuestionType"];
            options?: string[];
        };
        ClarifyResponse: {
            courseName: string;
            questions: components["schemas"]["ClarifyQuestion"][];
        };
        CourseAnswer: {
            questionId: string;
            answer: string;
        };
        CourseLesson: {
            name: string;
            description: string;
        };
        CourseModule: {
            name: string;
            description: string;
            lessons: components["schemas"]["CourseLesson"][];
        };
        StructureReasoning: {
            learnerProfile: string;
            topicAnalysis: string;
            scopeDecisions: string;
            progressionStrategy: string;
        };
        GenerateStructureResponse: {
            courseName: string;
            reasoning: components["schemas"]["StructureReasoning"];
            modules: components["schemas"]["CourseModule"][];
        };
        DepthPreview: {
            summary: string;
            bullets: string[];
        };
        DepthPreviewsResponse: {
            overview: components["schemas"]["DepthPreview"];
            comprehensive: components["schemas"]["DepthPreview"];
            deep_dive: components["schemas"]["DepthPreview"];
            recommended: components["schemas"]["CourseDepth"];
            recommendationReason: string;
        };
        JobStatus: {
            status: components["schemas"]["JobStatusEnum"];
            type: components["schemas"]["JobType"];
            courseId: string;
            error?: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        LessonBlock: {
            id: string;
            type: components["schemas"]["BlockType"];
            content: string;
            metadata: {
                [key: string]: unknown;
            } | null;
            order: number;
        };
        LessonContent: {
            _id: string;
            courseId: string;
            moduleIndex: number;
            lessonIndex: number;
            blocks: components["schemas"]["LessonBlock"][];
            heroImageUrl?: string | null;
            includeHeroImage?: boolean;
            audioUrl?: string | null;
            summary?: string | null;
            version: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        QuizResponse: {
            blockId: string;
            selectedOption: number;
            correct: boolean;
            /** Format: date-time */
            answeredAt?: string;
        };
        ExerciseAttempt: {
            blockId: string;
            code: string;
            passed: boolean;
            /** Format: date-time */
            attemptedAt?: string;
        };
        UserLessonProgress: {
            _id: string;
            userId: string;
            courseId: string;
            moduleIndex: number;
            lessonIndex: number;
            status: components["schemas"]["LessonProgressStatus"];
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            lastAccessedAt: string;
            timeSpentSeconds: number;
            quizResponses: components["schemas"]["QuizResponse"][];
            exerciseAttempts: components["schemas"]["ExerciseAttempt"][];
            notes?: string | null;
            bookmarked: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CourseProgressStats: {
            total: number;
            completed: number;
            inProgress?: number;
            percentage: number;
        };
        ModuleQuizQuestion: {
            id: string;
            question: string;
            options: string[];
            sourceLessons: number[];
            isInterleaved: boolean;
            interleavedModuleIndex?: number;
        };
        ModuleQuizContent: {
            courseId: string;
            moduleIndex: number;
            questions: components["schemas"]["ModuleQuizQuestion"][];
            version: number;
        };
        QuizAttemptQuestionResult: {
            id: string;
            question: string;
            options: string[];
            correctIndex: number;
            explanation: string;
            sourceLessons: number[];
            isInterleaved: boolean;
            interleavedModuleIndex?: number;
            selectedOption: number | null;
            correct: boolean;
        };
        QuizAttemptResult: {
            attemptNumber: number;
            score: number;
            masteryTier: components["schemas"]["QuizMasteryTier"];
            /** Format: date-time */
            completedAt: string;
            questions: components["schemas"]["QuizAttemptQuestionResult"][];
            /** Format: date-time */
            nextReviewAt: string;
            reviewIntervalDays: number;
        };
        QuizAttempt: {
            attemptNumber: number;
            score: number;
            masteryTier: components["schemas"]["QuizMasteryTier"];
            /** Format: date-time */
            completedAt: string;
            quizVersion: number;
        };
        UserModuleQuizProgress: {
            _id: string;
            userId: string;
            courseId: string;
            moduleIndex: number;
            attempts: components["schemas"]["QuizAttempt"][];
            bestScore: number;
            bestTier: components["schemas"]["QuizMasteryTier"] | null;
            reviewIntervalDays?: number;
            consecutiveSuccesses?: number;
            /** Format: date-time */
            nextReviewAt?: string | null;
        };
        CourseQuizProgressItem: {
            moduleIndex: number;
            bestScore: number;
            bestTier: components["schemas"]["QuizMasteryTier"] | null;
            attemptCount: number;
            /** Format: date-time */
            nextReviewAt: string | null;
            reviewDue: boolean;
        };
        ReviewDueItem: {
            courseId: string;
            courseSlug: string | null;
            courseName: string;
            moduleIndex: number;
            moduleName: string;
            bestScore: number;
            bestTier: components["schemas"]["QuizMasteryTier"];
            /** Format: date-time */
            nextReviewAt: string | null;
            reviewReason: components["schemas"]["ReviewReason"];
        };
        /** @enum {string} */
        XpSource: "lesson_complete" | "quiz_score" | "exercise_pass" | "review_complete" | "insight_review" | "insight_mastery";
        /** @enum {string} */
        AchievementCategory: "milestone" | "streak" | "mastery" | "dedication";
        EarnedAchievement: {
            achievementId: string;
            /** Format: date-time */
            earnedAt: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        XpLogEntry: {
            date: string;
            xp: number;
            source: components["schemas"]["XpSource"];
        };
        GamificationProfile: {
            userId: string;
            totalXp: number;
            level: number;
            xpForNextLevel: number;
            currentStreak: number;
            longestStreak: number;
            lastActiveDate?: string | null;
            earnedAchievements: components["schemas"]["EarnedAchievement"][];
            activeDates?: string[];
            xpLog?: components["schemas"]["XpLogEntry"][];
        };
        WeeklySummaryPeriod: {
            xp: number;
            timeSeconds: number;
            lessons: number;
            quizzes: number;
            insights: number;
        };
        GamificationStats: {
            xpByDay: {
                date: string;
                xp: number;
            }[];
            xpByWeek: {
                week: string;
                xp: number;
            }[];
            totalTimeLearned: number;
            lessonsThisWeek: number;
            weeklySummary?: {
                thisWeek: components["schemas"]["WeeklySummaryPeriod"];
                lastWeek: components["schemas"]["WeeklySummaryPeriod"];
            };
        };
        Course: {
            _id: string;
            userId: string;
            name: string;
            slug: string | null;
            status: components["schemas"]["CourseStatus"];
            goal: string;
            domain?: components["schemas"]["CourseDomain"] | null;
            clarifyData?: components["schemas"]["ClarifyResponse"];
            answers?: Record<string, never>;
            depth?: components["schemas"]["CourseDepth"];
            depthPreviews?: components["schemas"]["DepthPreviewsResponse"];
            structure?: components["schemas"]["GenerateStructureResponse"];
            feedbackHistory?: string[];
            pendingFeedback?: string;
            currentStep?: number;
            activeJobId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        InsightKind: "qa" | "cloze";
        /** @enum {string} */
        InsightMode: "tap-reveal" | "typed-recall";
        /** @enum {string} */
        InsightState: "new" | "learning" | "review" | "relearning";
        /**
         * @description 1=Again, 2=Hard, 3=Good, 4=Easy
         * @enum {integer}
         */
        InsightRating: 1 | 2 | 3 | 4;
        InsightQueueItem: {
            insightId: string;
            courseId: string;
            courseSlug: string | null;
            courseName: string;
            lessonId: string;
            moduleIndex: number;
            lessonIndex: number;
            lessonName: string;
            moduleName: string;
            kind: components["schemas"]["InsightKind"];
            prompt: string;
            answer: string;
            conceptTags: string[];
            sourceBlockId: string;
            isNew: boolean;
            mode: components["schemas"]["InsightMode"];
            box: number;
            /** Format: date-time */
            dueAt: string | null;
        };
        InsightQueue: {
            due: components["schemas"]["InsightQueueItem"][];
            fresh: components["schemas"]["InsightQueueItem"][];
            counts: {
                dueTotal: number;
                freshAvailable: number;
                learned: number;
            };
        };
        RateInsightResult: {
            box: number;
            state: components["schemas"]["InsightState"];
            reps: number;
            lapses: number;
            /** Format: date-time */
            nextDue: string;
            /** Format: date-time */
            lastReview: string | null;
            /** Format: date-time */
            masteredAt?: string | null;
            /** @description True exactly once per insight, when this rating first reached Leitner box 4. Never true on re-mastery. */
            justMastered?: boolean;
        };
        /** @enum {string} */
        GradeVerdict: "correct" | "partial" | "incorrect";
        GradeResult: {
            score: number;
            verdict: components["schemas"]["GradeVerdict"];
            feedback: string;
        };
        InsightStats: {
            totalInsights: number;
            totalReviewed: number;
            /** @description Insights that reached Leitner box 4 at least once (masteredAt !== null) */
            totalMastered: number;
            reviewedThisWeek: number;
            reviewedLastWeek: number;
            dueToday: number;
            dueThisWeek: number;
            boxDistribution: {
                box: number;
                count: number;
            }[];
            recentHistory: {
                date: string;
                reviews: number;
                avgRating: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
