/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/delete-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the authenticated user's account and all associated data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                deleted: boolean;
                            };
                        };
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthorisedUser"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate or register via Google */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        idToken: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the email verification link */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification-authenticated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend verification email for authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a user's email address */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                message?: string;
                            };
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a chat message for course structure refinement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        messages: {
                            /** @enum {string} */
                            role?: "user" | "assistant";
                            content?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description SSE stream of chat response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate clarifying questions for a course */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all courses for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new course */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        goal: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single course by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a course and its associated jobs */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                deleted: boolean;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a course by ID */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        goal?: string;
                        answers?: Record<string, never>;
                        /** @enum {string} */
                        depth?: "overview" | "comprehensive" | "deep_dive";
                        /** @enum {string} */
                        status?: "creating" | "ready" | "archived";
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"];
                        };
                    };
                };
                /** @description Cannot transition accepted course back to creating */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/course/execute-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute code via Judge0 sandbox */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        language: string;
                        stdin?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                stdout?: string | null;
                                stderr?: string | null;
                                compile_output?: string | null;
                                status?: string;
                                time?: string | null;
                                memory?: number | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/depth-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate personalized depth level previews */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generate-lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate content for a specific lesson */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        moduleIndex: number;
                        lessonIndex: number;
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a module quiz (or regenerate for retakes) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generate-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate course structure with modules and lessons */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chat history for course structure refinement */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                messages: {
                                    /** @enum {string} */
                                    role?: "user" | "assistant";
                                    content?: string;
                                    /** Format: date-time */
                                    createdAt?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the most recently accessed lesson across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId?: string;
                                courseName?: string;
                                courseGoal?: string;
                                moduleName?: string;
                                lessonName?: string;
                                moduleIndex?: number;
                                lessonIndex?: number;
                                courseProgress?: components["schemas"]["CourseProgressStats"];
                            } | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lesson progress for a course with aggregate stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                lessons: components["schemas"]["UserLessonProgress"][];
                                stats: components["schemas"]["CourseProgressStats"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/edit-impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assess the impact of editing a course (content and progress that would be lost) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                hasContent?: boolean;
                                hasProgress?: boolean;
                                completedLessons?: number;
                                inProgressLessons?: number;
                                totalNotes?: number;
                                totalBookmarks?: number;
                                quizAttempts?: number;
                                modulesWithMastery?: number;
                                scheduledReviews?: number;
                                totalTimeSpentMinutes?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/generated-lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of lessons that have generated content */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                moduleIndex: number;
                                lessonIndex: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/job/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status for polling */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["JobStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/lesson-content/{moduleIndex}/{lessonIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generated content for a specific lesson */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                    lessonIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["LessonContent"];
                        };
                    };
                };
                /** @description Lesson content not yet generated */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get module quiz content (correctIndex and explanation stripped for anti-cheat) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get quiz progress (attempts, best score, mastery tier) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/progress-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get progress percentage for all user courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                courseId: string;
                                total: number;
                                completed: number;
                                percentage: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/reviews-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all module quizzes due for review across all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: unknown[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/refine-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refine course structure based on learner feedback */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        feedback: string;
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                jobId: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/stream-lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate and stream lesson content via SSE (block-by-block) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        moduleIndex: number;
                        lessonIndex: number;
                    };
                };
            };
            responses: {
                /** @description SSE stream of lesson generation events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/module-quiz/{moduleIndex}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit quiz attempt — grades answers and returns results with explanations */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        responses: {
                            questionId: string;
                            selectedOption: number;
                        }[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{courseId}/progress/{moduleIndex}/{lessonIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert lesson progress (mark complete, update notes, track time, etc.) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                    moduleIndex: number;
                    lessonIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "not_started" | "in_progress" | "completed";
                        notes?: string | null;
                        bookmarked?: boolean;
                        /** @description Seconds to add to cumulative time */
                        timeSpentDelta?: number;
                        quizResponse?: components["schemas"]["QuizResponse"];
                        exerciseAttempt?: components["schemas"]["ExerciseAttempt"];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserLessonProgress"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            message: string;
            /** @enum {string} */
            errorCode?: "CUSTOM_ERROR" | "EMAIL_NOT_VERIFIED" | "EMAIL_ALREADY_VERIFIED" | "EMAIL_VERIFICATION_EXPIRED" | "EMAIL_VERIFICATION_INVALID";
        };
        AuthProvider: {
            /** @enum {string} */
            provider: "GOOGLE" | "CREDENTIALS";
            providerId?: string;
        };
        AuthorisedUser: {
            _id: string;
            email: string;
            name?: string;
            image?: string;
            emailVerified: boolean;
            authProviders: components["schemas"]["AuthProvider"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClarifyQuestion: {
            id: string;
            question: string;
            /** @enum {string} */
            type: "multiple_choice" | "multiple_select" | "text";
            options?: string[];
        };
        ClarifyResponse: {
            courseName: string;
            questions: components["schemas"]["ClarifyQuestion"][];
        };
        CourseAnswer: {
            questionId: string;
            answer: string;
        };
        CourseLesson: {
            name: string;
            description: string;
        };
        CourseModule: {
            name: string;
            description: string;
            lessons: components["schemas"]["CourseLesson"][];
        };
        StructureReasoning: {
            learnerProfile: string;
            topicAnalysis: string;
            scopeDecisions: string;
            progressionStrategy: string;
        };
        GenerateStructureResponse: {
            courseName: string;
            reasoning: components["schemas"]["StructureReasoning"];
            modules: components["schemas"]["CourseModule"][];
        };
        DepthPreview: {
            summary: string;
            bullets: string[];
        };
        DepthPreviewsResponse: {
            overview: components["schemas"]["DepthPreview"];
            comprehensive: components["schemas"]["DepthPreview"];
            deep_dive: components["schemas"]["DepthPreview"];
            /** @enum {string} */
            recommended: "overview" | "comprehensive" | "deep_dive";
            recommendationReason: string;
        };
        JobStatus: {
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed";
            /** @enum {string} */
            type: "clarify" | "generate_structure" | "refine_structure" | "generate_lesson" | "generate_depth_previews" | "generate_module_quiz";
            courseId: string;
            error?: string;
        };
        LessonBlock: {
            id: string;
            /** @enum {string} */
            type: "intro" | "section" | "code" | "mermaid" | "callout" | "quiz" | "exercise" | "summary" | "links" | "image";
            content: string;
            metadata?: Record<string, never> | null;
            order: number;
        };
        LessonContent: {
            _id: string;
            courseId: string;
            moduleIndex: number;
            lessonIndex: number;
            blocks: components["schemas"]["LessonBlock"][];
            heroImageUrl?: string | null;
            audioUrl?: string | null;
            summary?: string | null;
            version: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        QuizResponse: {
            blockId: string;
            selectedOption: number;
            correct: boolean;
            /** Format: date-time */
            answeredAt?: string;
        };
        ExerciseAttempt: {
            blockId: string;
            code: string;
            passed: boolean;
            /** Format: date-time */
            attemptedAt?: string;
        };
        UserLessonProgress: {
            _id: string;
            userId: string;
            courseId: string;
            moduleIndex: number;
            lessonIndex: number;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "completed";
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            lastAccessedAt?: string;
            timeSpentSeconds?: number;
            quizResponses?: components["schemas"]["QuizResponse"][];
            exerciseAttempts?: components["schemas"]["ExerciseAttempt"][];
            notes?: string | null;
            bookmarked?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CourseProgressStats: {
            total: number;
            completed: number;
            inProgress?: number;
            percentage: number;
        };
        Course: {
            _id: string;
            userId: string;
            name: string;
            /** @enum {string} */
            status: "creating" | "ready" | "archived";
            goal: string;
            clarifyData?: components["schemas"]["ClarifyResponse"];
            answers?: Record<string, never>;
            /** @enum {string} */
            depth?: "overview" | "comprehensive" | "deep_dive";
            depthPreviews?: components["schemas"]["DepthPreviewsResponse"];
            structure?: components["schemas"]["GenerateStructureResponse"];
            feedbackHistory?: string[];
            pendingFeedback?: string;
            currentStep?: number;
            activeJobId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
