# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Knowledge Base: Sync - Technical'

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-technical:
    uses: Simas-Zurauskas/strive2-ci/.github/workflows/notion-sync-technical.yml@master
    secrets: inherit
