# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Knowledge Base: Rebuild - Product'

on:
  workflow_dispatch:

jobs:
  rebuild:
    uses: Simas-Zurauskas/strive2-ci/.github/workflows/notion-rebuild-product.yml@master
    secrets: inherit
